### Update person = 1
PUT http://localhost:8080/persons/1
Content-Type: application/json

{
  "firstName": "Cezary",
  "lastName": "Bandurowicz",
  "sex": "M",
  "comments": "person comments 1"
}

### Update relation = 2
PUT http://localhost:8080/relations/2
Content-Type: application/json

{
  "person1": 1,
  "person2": 3,
  "relationType1": "father",
  "relationType2": "children",
  "comments": "relation comments 2"
}

### Update document = 2
PUT http://localhost:8080/documents/2
Content-Type: application/json

{
  "person1": "2",
  "documentType": "MARRIAGE_CERTIFICATE",
  "comments": "akt małżeństwa po up"
}

### Update events = 2
PUT http://localhost:8080/events/2
Content-Type: application/json

{
  "person1": "2",
  "eventType": "MARRIAGE",
  "comments": "ślub po up",
  "eventDate": "2020-01-02"
}