### Create person = 1
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Cezaryy",
  "secondName": "Dawid",
  "lastName": "Nowak",
  "sex": "M",
  "comments": "person 1 comments"
}

### Create person = 2
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Elżbieta",
  "secondName": "Maria",
  "lastName": "Nowak",
  "maidenName": "Kuchta",
  "sex": "F",
  "comments": "person 2 comments"
}

### Create person = 3
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Mariusz",
  "lastName": "Nowak",
  "sex": "M",
  "comments": "person 3 comments"
}

### Create person = 4
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Damian",
  "lastName": "Nowak",
  "sex": "M",
  "comments": "person 4 comments"
}

### Create person = 5
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Szczepan",
  "lastName": "Nowak",
  "sex": "M",
  "comments": "person 5 comments"
}

### Create person = 6
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Wiesława",
  "lastName": "Nowak",
  "maidenName": "Krud",
  "sex": "F",
  "comments": "person 6 comments"
}

### Create person = 7
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Agnieszka",
  "lastName": "Dron",
  "maidenName": "Nowak",
  "sex": "F",
  "comments": "person 7 comments"
}

### Create person = 8
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Zofia",
  "secondName": "Ewa",
  "lastName": "Krus",
  "maidenName": "Malek",
  "sex": "F",
  "comments": "person 8 comments"
}

### Create person = 9
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Wojciechk",
  "secondName": "Jan",
  "lastName": "Krus",
  "sex": "M",
  "comments": "person 9 comments"
}

### Create person = 10
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "Malek",
  "sex": "M",
  "comments": "person 10 comments"
}

### Create person = 11
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Janina",
  "lastName": "Malek",
  "maidenName": "Kazik",
  "sex": "M",
  "comments": "person 11 comments"
}

### Create person = 12
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Mirosław",
  "secondName": "Tomasz",
  "lastName": "Krus",
  "sex": "M",
  "comments": "person 12 comments"
}

### Create person = 13
POST http://localhost:8080/persons
Content-Type: application/json

{
  "firstName": "Władysława",
  "secondName": "Anna",
  "lastName": "Krus",
  "maidenName": "Dąbrowska",
  "sex": "F",
  "comments": "person 13 comments"
}


### Create relation = 1
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 2,
  "relationType1": "husband",
  "relationType2": "wife",
  "comments": "relation 1 comments"
}

### Create relation = 2
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 3,
  "relationType1": "siblings",
  "relationType2": "siblings",
  "comments": "relation 2 comments"
}

### Create relation = 3
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 4,
  "relationType1": "father",
  "relationType2": "children",
  "comments": "relation 3 comments"
}

### Create relation = 4
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 5,
  "relationType1": "children",
  "relationType2": "father",
  "comments": "relation 4 comments"
}

### Create relation = 5
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 6,
  "relationType1": "children",
  "relationType2": "mother",
  "comments": "relation 5 comments"
}

### Create relation = 6
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 1,
  "person2": 7,
  "relationType1": "siblings",
  "relationType2": "siblings",
  "comments": "relation 6 comments"
}

### Create relation = 7
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 7,
  "person2": 6,
  "relationType1": "children",
  "relationType2": "mother",
  "comments": "relation 7 comments"
}

### Create relation = 8
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 2,
  "person2": 4,
  "relationType1": "mother",
  "relationType2": "children",
  "comments": "relation 8 comments"
}

### Create relation = 9
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 8,
  "person2": 2,
  "relationType1": "mother",
  "relationType2": "children",
  "comments": "relation 9 comments"
}

### Create relation = 10
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 9,
  "person2": 2,
  "relationType1": "father",
  "relationType2": "children",
  "comments": "relation 10 comments"
}

### Create relation = 11
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 10,
  "person2": 8,
  "relationType1": "father",
  "relationType2": "children",
  "comments": "relation 11 comments"
}

### Create relation = 12
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 11,
  "person2": 8,
  "relationType1": "mother",
  "relationType2": "children",
  "comments": "relation 12 comments"
}

### Create relation = 13
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 12,
  "person2": 9,
  "relationType1": "father",
  "relationType2": "children",
  "comments": "relation 13 comments"
}

### Create relation = 14
POST http://localhost:8080/relations
Content-Type: application/json

{
  "person1": 13,
  "person2": 9,
  "relationType1": "mother",
  "relationType2": "children",
  "comments": "relation 14 comments"
}


### Create document = 1
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "BIRTH_CERTIFICATE",
  "comments": "BIRTH_CERTIFICATE"
}

### Create document = 2
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "DEATH_CERTIFICATE",
  "comments": "DEATH_CERTIFICATE"
}

### Create document = 3
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "ID_DOCUMENT",
  "comments": "first ID"
}

### Create document = 3
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "ID_DOCUMENT",
  "comments": "second ID"
}

### Create document = 5
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "MARRIAGE_CERTIFICATE",
  "comments": "first MARRIAGE_CERTIFICATE"
}

### Create document = 6
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "MARRIAGE_CERTIFICATE",
  "comments": "second MARRIAGE_CERTIFICATE"
}

### Create document = 7
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "OTHER_DOCUMENT",
  "comments": "first OTHER_DOCUMENT"
}

### Create document = 8
POST http://localhost:8080/documents
Content-Type: application/json

{
  "person1": "2",
  "documentType": "OTHER_DOCUMENT",
  "comments": "second OTHER_DOCUMENT"
}

### Create event = 1
POST http://localhost:8080/events
Content-Type: application/json

{
  "person1": "2",
  "eventDate": "1960-12-31",
  "eventType": "BIRTH",
  "comments": "BIRTH"
}

### Create event = 2
POST http://localhost:8080/events
Content-Type: application/json

{
  "person1": "2",
  "eventDate": "1990-12-31",
  "eventType": "DEATH",
  "comments": "DEATH"
}

### Create event = 3
POST http://localhost:8080/events
Content-Type: application/json

{
  "person1": "3",
  "eventDate": "1980-12-31",
  "eventType": "MARRIAGE",
  "comments": "first MARRIAGE"
}

### Create event = 4
POST http://localhost:8080/events
Content-Type: application/json

{
  "person1": "3",
  "eventDate": "1985-12-31",
  "eventType": "MARRIAGE",
  "comments": "second MARRIAGE"
}