### Delete person = 21
DELETE http://localhost:8080/persons/21

### Delete relation = 21
DELETE http://localhost:8080/relations/21

### Delete document = 21
DELETE http://localhost:8080/documents/21

### Delete events = 21
DELETE http://localhost:8080/events/21
