### Get person by id = 21
GET http://localhost:8080/persons/21

### Get relation by id = 21
GET http://localhost:8080/relations/21

### Get document by id = 21
GET http://localhost:8080/documents/21

### Get event by id = 21
GET http://localhost:8080/events/21